version: '2'
services:
    mysql:
        image: 'mysql:5.7'
        expose:
          - '3306'
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: on-failure
        env_file:
            - docker.env
    nginx:
        image: 'nginx:1.13'
        ports:
            - '80:80'
        restart: on-failure
        volumes:
            - ./docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/code
    php-fpm:
        build: ./docker-images/php-extended
        env_file:
          - docker.env
        restart: on-failure
        volumes:
            - ./docker-images/php-extended/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/code
    redis:
      image: bitnami/redis:latest
      user: root
      environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - ./data/redis:/bitnami
    mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'
    elasticsearch:
      image: elasticsearch:6.8.0
      ports:
        - "9200:9200"
        - "9300:9300"
      tty : true
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8090:80'
      env_file:
        - docker.env