version: "3.4"
services:
    mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      env_file:
        - docker.env
      volumes:
          - ${MYSQL_VOLUME:-./data/mysql}:/var/lib/mysql
    nginx:
        image: 'nginx:1.20'
        ports:
          - '80:80'
          - '443:443'
        restart: always
        volumes:
            - ${ROOT_DIR:-.}/:/var/www
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.crt:/etc/nginx/localhost.crt
            - ${BUILD_CONTEXT:-.}/docker-images/nginx-extended/ssl/localhost.key:/etc/nginx/localhost.key
    php-fpm:
        build:
          context: .
          dockerfile: ./docker-images/php-extended/Dockerfile
        image: "php-fpm"
        env_file:
          - docker.env
        restart: always
        volumes:
            - ${BUILD_CONTEXT:-.}/docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ${ROOT_DIR:-.}/:/var/www
        depends_on:
          - mysql
          - nginx
        command: [ "php-fpm" ]
    redis:
      image: bitnami/redis:latest
      user: root
      env_file:
        - docker.env
      volumes:
        - ${REDIS_VOLUME:-./data/redis}:/bitnami
    mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'
    elasticsearch:
      image: elasticsearch:6.8.0
      ports:
        - "9200:9200"
        - "9300:9300"
      tty : true
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8090:80'
      env_file:
        - docker.env