version: '2'
services:
    mysql:
        image: mysql:5.7
        expose:
          - '3307'
        ports:
            - '3307:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
        restart: on-failure
        env_file:
            - docker.env
    nginx:
        image: nginx:1.13
        ports:
            - '82:80'
        restart: on-failure
        volumes:
            - ./docker-images/nginx-extended/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/code
    php-fpm:
        build: ./docker-images/php-extended
        restart: on-failure
        volumes:
            - ./docker-images/php-extended/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/code
    redis:
      image: 'bitnami/redis:4.0.6-r1'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_PASSWORD=docker
      ports:
        - '6379:6379'
      volumes:
        - ./data/redis:/bitnami
        - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf
    mongodb:
      image: mongo:latest
      ports:
        - '27017:27017'
    pma:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
        - '8080:80'
      environment:
        - MYSQL_USER=docker
        - MYSQL_ROOT_PASSWORD=docker 
        - PMA_HOST=mysql

